### ISSUE TITLE
Define standard format for References

### ISSUE THREAD

**Issue by mrdrewkeller** [usnistgov/mobile-threat-catalogue#98]
If we define a standard format for references, we can eliminate formatting issues in the current ``references.md`` file and instead format them in a template.

**Comment by mrdrewkeller** [comment]
@sdog-nist Any thoughts on the template below?

``` yml
---
-
    referenceID:
    author:
    title:
    source:
    publicationYear:
    pageStart:
    pageEnd:
    url:
    accessDate:
```
